### ISSUE TITLE
Comment section for `Why don't I have a blog?'

### ISSUE THREAD

**Issue by FdelMazo** [FdelMazo/blog#1]
Every comment in this issue will appear on the [blog](https://fede.dm/blog/). Thanks for the [idea](http://donw.io/post/github-comments/) @dwilliamson!

**Comment by Ellipse0934** [comment]
Your post starts by mentioning very famous people in the tech community. That's a high bar you're setting for yourself. Have you never come across a blog by a "nobody" who just has 2-3 posts published in 2012 but happens to be an interesting read ? Or happens to explain a concept more elegantly than mainstream sources ? Or maybe the post is just a bunch of pointers to good resources with a brief notes ?

You wrote an interesting blog post. I disagree with your conclusion and your opinion on your opinion (that you don't have anything interesting to say). I would've pressed the RSS feed button (if it existed).

If you don't enjoy writing then you don't enjoy it. But, maybe just the act of writing to recollect your thoughts is something that may be of help to you.

Btw, did you enjoy writing this post ? :thinking:

**Comment by bewuethr** [comment]
You're asking for book recommendations, and based on *UNIX: A History and a Memoir*, you might also enjoy [*The Idea Factory*](https://www.goodreads.com/book/show/11797471-the-idea-factory) about Bell Labs, or [*Where Wizards Stay Up Late*](https://www.goodreads.com/book/show/281818.Where_Wizards_Stay_Up_Late) about the history of the internet.

**Comment by breno-costa** [comment]
You have a blog.

**Comment by triptych** [comment]
This post feels strongly to  me that you do have what it takes to write a blog, and that it would have value to the folks reading it. You're thoughtful and organized, and to be honest it takes time to find your voice. Write a blog for your own sake and don't worry about what value add you are doing for others. The benefits of putting your thoughts down in a blog are valuable in  their own right - to  help you learn to write better.

**Comment by chris-short** [comment]
I gotta say, I thought my blog would help but it’s a long game that you can play. But, things took off for me when I started a newsletter.

**Comment by LinuxFan2718** [comment]
You would like [The Dream Machine by M Mitchell Waldrop](https://www.goodreads.com/en/book/show/722412.The_Dream_Machine)

**Comment by x0ul** [comment]
i have no idea who you are but this resonates with me, great blog post
